version: '3.8'

services:
  db:
    image: postgres:15
    container_name: notes_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - notes_data:/var/lib/postgresql/data
    networks:
      - notes-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: notes_app
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
    depends_on:
      - db
    networks:
      - notes-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: notes_frontend
    ports:
      - "3000:80" # React default port is 3000, Nginx serves on 80
    depends_on:
      - backend
    networks:
      - notes-network

volumes:
  notes_data:

networks:
  notes-network:
    driver: bridge
