version: "3.9"

services:
  app:
    build:
      context: ../../backend
    container_name: notes_app
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: notes_db
    environment:
      POSTGRES_USER: notesuser
      POSTGRES_PASSWORD: notespass
      POSTGRES_DB: notesdb
    ports:
      - "5432:5432"
    volumes:
      - notes_data:/var/lib/postgresql/data

volumes:
  notes_data: